import { existsSync, readFileSync, statSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import type { AnySchemaObject } from 'ajv';
import type { Config, SpaceConfig } from '../config';
import { PLUGIN_PREFIX as _PLUGIN_PREFIX } from '../constants';
import type { PluginSchemaSource } from '../schema/schema';
import type { SpaceGraph } from '../space-graph';
import type { BaseNode, ParseIssue, SpaceContext } from '../types';

export const PLUGIN_PREFIX = _PLUGIN_PREFIX;
export const CONFIG_PLUGINS_DIR = 'plugins';

/** Normalize a plugin name to its canonical prefixed form. */
export function normalizePluginName(name: string): string {
  return name.startsWith(PLUGIN_PREFIX) ? name : `${PLUGIN_PREFIX}${name}`;
}

/** Shorten a plugin name to its non-prefixed form. */
export function shortenPluginName(name: string): string {
  return name.startsWith(PLUGIN_PREFIX) ? name.slice(PLUGIN_PREFIX.length) : name;
}

export type PluginContext = SpaceContext & {
  /** Validated config for this plugin invocation. */
  pluginConfig: Record<string, unknown>;
  /** Optional callback functions for plugins to interact with the system. */
  callbacks?: {
    /** Persist plugin config updates to the config file. */
    persistConfig?: (updates: Record<string, string>) => void;
  };
};

export type ParseResult = {
  nodes: BaseNode[];
  /** Issues encountered while parsing files — excluded files with reason and severity. */
  parseIssues: ParseIssue[];
  /** Plugin diagnostics: keyed scalar or list values. */
  diagnostics: Record<string, number | string | string[]>;
};

export type ParseHook = (context: PluginContext) => Promise<ParseResult | null>;

export type TemplateSyncOptions = {
  dryRun?: boolean;
  createMissing?: boolean;
};

export type TemplateSyncHook = (context: PluginContext, options: TemplateSyncOptions) => Promise<true | null>;

/** A single render output format provided by a plugin. */
export type RenderFormat = {
  /** Short name, unique within the plugin (e.g. 'bullets', 'mermaid'). */
  name: string;
  /** Human-readable description shown in `render list`. */
  description: string;
};

/** Options passed to a render function. */
export type RenderOptions = {
  /** The format name being rendered (e.g. 'bullets', 'mermaid'). */
  format: string;
  /** Plugin-specific extra data (e.g. CLI flags forwarded by a convenience command). */
  data?: Record<string, unknown>;
};

/** A single file generated as part of a multi-file render output. */
export type RenderFileOutput = {
  /** Relative path of the file within the destination directory (e.g. 'goals/My Goal.md'). */
  path: string;
  /** File content to write. */
  content: string;
};

/** Multi-file render output generated by a render hook. */
export type RenderMultiFileOutput = {
  files: RenderFileOutput[];
};

/** Render hook output: either a single string (stdout/single file) or multiple files. */
export type RenderResult = string | RenderMultiFileOutput;

/** Type guard for multi-file render result. */
export function isRenderMultiFileOutput(result: RenderResult): result is RenderMultiFileOutput {
  return typeof result === 'object' && result !== null && Array.isArray((result as RenderMultiFileOutput).files);
}

/**
 * The render hook on a plugin: declares available formats and handles rendering.
 * Unlike parse/templateSync (first-responder), render hooks are additive —
 * all formats from all plugins are available simultaneously.
 */
export type RenderHook = {
  formats: RenderFormat[];
  render: (context: PluginContext, graph: SpaceGraph, options: RenderOptions) => Promise<RenderResult> | RenderResult;
};

/**
 * Plugin contract:
 * - A hook not implemented on the plugin → that plugin is skipped for that operation.
 * - parse/templateSync return `T | null` → null means "didn't handle, try next plugin".
 * - render is additive: all plugins' formats are registered and dispatched by name.
 */
export type StructuredContextPlugin = {
  name: string;
  /** JSON Schema used to validate the plugin's config block. Fields with `format: 'path'`
   * are resolved relative to the config directory by `resolveConfigPaths` in the loader. */
  configSchema: AnySchemaObject;
  /** Optional directory containing JSON schemas contributed by this plugin. */
  schemasDir?: string;
  parse?: ParseHook;
  templateSync?: TemplateSyncHook;
  render?: RenderHook;
};

/**
 * Synchronously locate the root directory of an external plugin.
 * Resolution order:
 * 1. Config-adjacent: {configDir}/plugins/{name} or {configDir}/plugins/sctx-{name}
 * 2. Node module: resolve from configDir using standard module resolution
 */
export function resolvePluginDir(pluginName: string, configDir: string): string | undefined {
  const normalized = normalizePluginName(pluginName);
  const short = shortenPluginName(pluginName);

  for (const candidate of [normalized, short]) {
    const localDir = resolve(configDir, CONFIG_PLUGINS_DIR, candidate);
    if (existsSync(localDir)) {
      try {
        if (statSync(localDir).isDirectory()) {
          return localDir;
        }
      } catch {}
    }
  }

  // Node module resolution from configDir
  for (const candidate of [normalized, short]) {
    try {
      const req = createRequire(join(configDir, 'package.json'));
      const pkgPath = req.resolve(`${candidate}/package.json`);
      return dirname(pkgPath);
    } catch {
      const nmCandidate = resolve(configDir, 'node_modules', candidate);
      if (existsSync(nmCandidate)) {
        try {
          if (statSync(nmCandidate).isDirectory()) {
            return nmCandidate;
          }
        } catch {}
      }
    }
  }

  return undefined;
}

/**
 * Synchronously locate the schemas directory for a plugin.
 * Convention:
 * 1. package.json "sctx": { "schemas": "..." }
 * 2. Convention: <pluginDir>/schemas
 * 3. Fallback for test fixtures: {configDir}/plugins/schemas
 */
export function resolvePluginSchemasDir(pluginName: string, configDir: string): string | undefined {
  const dir = resolvePluginDir(pluginName, configDir);
  if (dir) {
    // 1. package.json sctx.schemas
    const pkgJsonPath = join(dir, 'package.json');
    if (existsSync(pkgJsonPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgJsonPath, 'utf8'));
        if (pkg.sctx?.schemas && typeof pkg.sctx.schemas === 'string') {
          const customSchemas = resolve(dir, pkg.sctx.schemas);
          if (existsSync(customSchemas) && statSync(customSchemas).isDirectory()) {
            return customSchemas;
          }
        }
      } catch {}
    }

    // 2. Convention: <pluginDir>/schemas
    const conventionDir = join(dir, 'schemas');
    if (existsSync(conventionDir)) {
      try {
        if (statSync(conventionDir).isDirectory()) {
          return conventionDir;
        }
      } catch {}
    }
  }

  // 3. Check config-adjacent plugins/schemas as fallback (e.g. test fixtures)
  const fallbackSchemas = resolve(configDir, CONFIG_PLUGINS_DIR, 'schemas');
  if (existsSync(fallbackSchemas)) {
    try {
      if (statSync(fallbackSchemas).isDirectory()) {
        return fallbackSchemas;
      }
    } catch {}
  }

  return undefined;
}

/**
 * Synchronously collect all plugin schema sources available to a space.
 */
export function resolveSpacePluginSchemas(
  space: SpaceConfig | undefined,
  config: Config,
  configDir: string,
): PluginSchemaSource[] {
  const pluginSources: PluginSchemaSource[] = [];
  const seenPlugins = new Set<string>();

  const maybeAddPlugin = (name: string) => {
    const shortName = shortenPluginName(name);
    if (seenPlugins.has(shortName)) return;
    seenPlugins.add(shortName);

    const schemasDir = resolvePluginSchemasDir(name, configDir);
    if (schemasDir) {
      pluginSources.push({
        pluginName: shortName,
        schemasDir,
      });
    }
  };

  // 1. Plugin referenced by space.schema prefix if any (e.g. sctx-wardley-mapping/wardley_map.json)
  const rawSchema = space?.schema ?? config.schema;
  if (rawSchema && !isAbsolute(rawSchema) && !rawSchema.startsWith('.')) {
    const normalized = rawSchema.replace(/\\/g, '/');
    const slashIdx = normalized.indexOf('/');
    if (slashIdx !== -1) {
      const prefix = normalized.slice(0, slashIdx);
      maybeAddPlugin(prefix);
    }
  }

  // 2. Plugins configured on space
  if (space?.plugins) {
    for (const name of Object.keys(space.plugins)) {
      maybeAddPlugin(name);
    }
  }

  // 3. Plugins configured globally
  const globalPlugins = (config as { plugins?: Record<string, unknown> }).plugins;
  if (globalPlugins) {
    for (const name of Object.keys(globalPlugins)) {
      maybeAddPlugin(name);
    }
  }

  return pluginSources;
}
